In [36]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.linear_model import  LinearRegression

In [37]:
df=sns.load_dataset('tips')

In [38]:
df.head()


total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [39]:
X=df[['total_bill']]
y=df['tip']

In [40]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,train_size=0.8)

In [41]:
model=LinearRegression()

In [42]:
#Training the model

model.fit(X_train,y_train)

LinearRegression()

In [43]:
y_pred=model.predict(X_test)
y_pred

array([2.60022524, 3.01040093, 2.72037771, 4.55166714, 2.52046886,
       2.6520151 , 3.31078211, 3.62566446, 2.89335584, 3.64430881,
       2.25323318, 2.71623452, 2.27394912, 3.58112518, 2.07818346,
       3.45682951, 3.58216097, 2.85399555, 3.5738746 , 2.33816855,
       3.37914473, 2.14136708, 3.10569427, 2.35266971, 3.32010429,
       4.31861278, 2.61783379, 2.0263936 , 3.41539763, 3.31906849,
       1.71358285, 3.76446128, 2.75352322, 2.2822355 , 2.00567765,
       3.45475792, 3.96954912, 4.07623623, 4.54959555, 2.49353813,
       4.05448449, 2.93893092, 4.26164393, 5.95206494, 2.58779567,
       4.04930551, 3.71681461, 3.74478113, 2.02846519])

In [45]:
#Prediction
model.predict([[20]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([3.03422426])

In [48]:
# prompt: evaluate the model using root mean squared error and mean absolute error

from sklearn.metrics import mean_squared_error, mean_absolute_error

# Calculate root mean squared error
rmse = np.sqrt(mean_squared_error(y_test, y_pred))

# Calculate mean absolute error
mae = mean_absolute_error(y_test, y_pred)

print("Root mean squared error:", rmse)
print("Mean absolute error:", mae)


Root mean squared error: 0.9538193939380093
Mean absolute error: 0.790121292647169


In [49]:
# prompt: save the model

import pickle
with open('model.pkl', 'wb') as file:
  pickle.dump(model, file)


In [50]:
# prompt: import the model

import pickle

with open('model.pkl', 'rb') as file:
  model = pickle.load(file)


In [51]:
model.predict([[500]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([52.75248932])